export class TailwindTheme {
  themeName?: string = ''
  /** twAspectRatio - https://tailwindcss.com/docs/aspect-ratio*/
  twAspectRatio?: string = ''
  /** twContainer - https://tailwindcss.com/docs/container*/
  twContainer?: string = ''
  /** twColumns - https://tailwindcss.com/docs/columns*/
  twColumns?: string = ''
  /** twBreakAfter - https://tailwindcss.com/docs/break-after*/
  twBreakAfter?: string = ''
  /** twBreakBefore - https://tailwindcss.com/docs/break-before*/
  twBreakBefore?: string = ''
  /** twBreakInside - https://tailwindcss.com/docs/break-inside*/
  twBreakInside?: string = ''
  /** twBoxDecorationBreak - https://tailwindcss.com/docs/box-decoration-break*/
  twBoxDecorationBreak?: string = ''
  /** twBoxSizing - https://tailwindcss.com/docs/box-sizing*/
  twBoxSizing?: string = ''
  /** twDisplay - https://tailwindcss.com/docs/display*/
  twDisplay?: string = ''
  /** twFloat - https://tailwindcss.com/docs/float*/
  twFloat?: string = ''
  /** twClear - https://tailwindcss.com/docs/clear*/
  twClear?: string = ''
  /** twIsolation - https://tailwindcss.com/docs/isolation*/
  twIsolation?: string = ''
  /** twObjectFit - https://tailwindcss.com/docs/object-fit*/
  twObjectFit?: string = ''
  /** twObjectPosition - https://tailwindcss.com/docs/object-position*/
  twObjectPosition?: string = ''
  /** twOverflow - https://tailwindcss.com/docs/overflow*/
  twOverflow?: string = ''
  /** twOverscrollBehavior - https://tailwindcss.com/docs/overscroll-behavior*/
  twOverscrollBehavior?: string = ''
  /** twPosition - https://tailwindcss.com/docs/position*/
  twPosition?: string = ''
  /** twTopRightBottomLeft - https://tailwindcss.com/docs/top-right-bottom-left*/
  twTopRightBottomLeft?: string = ''
  /** twVisibility - https://tailwindcss.com/docs/visibility*/
  twVisibility?: string = ''
  /** twZIndex - https://tailwindcss.com/docs/z-index*/
  twZIndex?: string = ''
  /** twFlexBasis - https://tailwindcss.com/docs/flex-basis*/
  twFlexBasis?: string = ''
  /** twFlexDirection - https://tailwindcss.com/docs/flex-direction*/
  twFlexDirection?: string = ''
  /** twFlexWrap - https://tailwindcss.com/docs/flex-wrap*/
  twFlexWrap?: string = ''
  /** twFlex - https://tailwindcss.com/docs/flex*/
  twFlex?: string = ''
  /** twFlexGrow - https://tailwindcss.com/docs/flex-grow*/
  twFlexGrow?: string = ''
  /** twFlexShrink - https://tailwindcss.com/docs/flex-shrink*/
  twFlexShrink?: string = ''
  /** twOrder - https://tailwindcss.com/docs/order*/
  twOrder?: string = ''
  /** twGridTemplateColumns - https://tailwindcss.com/docs/grid-template-columns*/
  twGridTemplateColumns?: string = ''
  /** twGridColumn - https://tailwindcss.com/docs/grid-column*/
  twGridColumn?: string = ''
  /** twGridTemplateRows - https://tailwindcss.com/docs/grid-template-rows*/
  twGridTemplateRows?: string = ''
  /** twGridRow - https://tailwindcss.com/docs/grid-row*/
  twGridRow?: string = ''
  /** twGridAutoFlow - https://tailwindcss.com/docs/grid-auto-flow*/
  twGridAutoFlow?: string = ''
  /** twGridAutoColumns - https://tailwindcss.com/docs/grid-auto-columns*/
  twGridAutoColumns?: string = ''
  /** twGridAutoRows - https://tailwindcss.com/docs/grid-auto-rows*/
  twGridAutoRows?: string = ''
  /** twGap - https://tailwindcss.com/docs/gap*/
  twGap?: string = ''
  /** twJustifyContent - https://tailwindcss.com/docs/justify-content*/
  twJustifyContent?: string = ''
  /** twJustifyItems - https://tailwindcss.com/docs/justify-items*/
  twJustifyItems?: string = ''
  /** twJustifySelf - https://tailwindcss.com/docs/justify-self*/
  twJustifySelf?: string = ''
  /** twAlignContent - https://tailwindcss.com/docs/align-content*/
  twAlignContent?: string = ''
  /** twAlignItems - https://tailwindcss.com/docs/align-items*/
  twAlignItems?: string = ''
  /** twAlignSelf - https://tailwindcss.com/docs/align-self*/
  twAlignSelf?: string = ''
  /** twPlaceContent - https://tailwindcss.com/docs/place-content*/
  twPlaceContent?: string = ''
  /** twPlaceItems - https://tailwindcss.com/docs/place-items*/
  twPlaceItems?: string = ''
  /** twPlaceSelf - https://tailwindcss.com/docs/place-self*/
  twPlaceSelf?: string = ''
  /** twPadding - https://tailwindcss.com/docs/padding*/
  twPadding?: string = ''
  /** twMargin - https://tailwindcss.com/docs/margin*/
  twMargin?: string = ''
  /** twSpace - https://tailwindcss.com/docs/space*/
  twSpace?: string = ''
  /** twWidth - https://tailwindcss.com/docs/width*/
  twWidth?: string = ''
  /** twMinWidth - https://tailwindcss.com/docs/min-width*/
  twMinWidth?: string = ''
  /** twMaxWidth - https://tailwindcss.com/docs/max-width*/
  twMaxWidth?: string = ''
  /** twHeight - https://tailwindcss.com/docs/height*/
  twHeight?: string = ''
  /** twMinHeight - https://tailwindcss.com/docs/min-height*/
  twMinHeight?: string = ''
  /** twMaxHeight - https://tailwindcss.com/docs/max-height*/
  twMaxHeight?: string = ''
  /** twSize - https://tailwindcss.com/docs/size*/
  twSize?: string = ''
  /** twFontFamily - https://tailwindcss.com/docs/font-family*/
  twFontFamily?: string = ''
  /** twFontSize - https://tailwindcss.com/docs/font-size*/
  twFontSize?: string = ''
  /** twFontSmoothing - https://tailwindcss.com/docs/font-smoothing*/
  twFontSmoothing?: string = ''
  /** twFontStyle - https://tailwindcss.com/docs/font-style*/
  twFontStyle?: string = ''
  /** twFontWeight - https://tailwindcss.com/docs/font-weight*/
  twFontWeight?: string = ''
  /** twFontVariantNumeric - https://tailwindcss.com/docs/font-variant-numeric*/
  twFontVariantNumeric?: string = ''
  /** twLetterSpacing - https://tailwindcss.com/docs/letter-spacing*/
  twLetterSpacing?: string = ''
  /** twLineClamp - https://tailwindcss.com/docs/line-clamp*/
  twLineClamp?: string = ''
  /** twLineHeight - https://tailwindcss.com/docs/line-height*/
  twLineHeight?: string = ''
  /** twListStyleImage - https://tailwindcss.com/docs/list-style-image*/
  twListStyleImage?: string = ''
  /** twListStylePosition - https://tailwindcss.com/docs/list-style-position*/
  twListStylePosition?: string = ''
  /** twListStyleType - https://tailwindcss.com/docs/list-style-type*/
  twListStyleType?: string = ''
  /** twTextAlign - https://tailwindcss.com/docs/text-align*/
  twTextAlign?: string = ''
  /** twTextColor - https://tailwindcss.com/docs/text-color*/
  twTextColor?: string = ''
  /** twTextDecoration - https://tailwindcss.com/docs/text-decoration*/
  twTextDecoration?: string = ''
  /** twTextDecorationColor - https://tailwindcss.com/docs/text-decoration-color*/
  twTextDecorationColor?: string = ''
  /** twTextDecorationStyle - https://tailwindcss.com/docs/text-decoration-style*/
  twTextDecorationStyle?: string = ''
  /** twTextDecorationThickness - https://tailwindcss.com/docs/text-decoration-thickness*/
  twTextDecorationThickness?: string = ''
  /** twTextUnderlineOffset - https://tailwindcss.com/docs/text-underline-offset*/
  twTextUnderlineOffset?: string = ''
  /** twTextTransform - https://tailwindcss.com/docs/text-transform*/
  twTextTransform?: string = ''
  /** twTextOverflow - https://tailwindcss.com/docs/text-overflow*/
  twTextOverflow?: string = ''
  /** twTextWrap - https://tailwindcss.com/docs/text-wrap*/
  twTextWrap?: string = ''
  /** twTextIndent - https://tailwindcss.com/docs/text-indent*/
  twTextIndent?: string = ''
  /** twVerticalAlign - https://tailwindcss.com/docs/vertical-align*/
  twVerticalAlign?: string = ''
  /** twWhitespace - https://tailwindcss.com/docs/whitespace*/
  twWhitespace?: string = ''
  /** twWordBreak - https://tailwindcss.com/docs/word-break*/
  twWordBreak?: string = ''
  /** twHyphens - https://tailwindcss.com/docs/hyphens*/
  twHyphens?: string = ''
  /** twContent - https://tailwindcss.com/docs/content*/
  twContent?: string = ''
  /** twBackgroundAttachment - https://tailwindcss.com/docs/background-attachment*/
  twBackgroundAttachment?: string = ''
  /** twBackgroundClip - https://tailwindcss.com/docs/background-clip*/
  twBackgroundClip?: string = ''
  /** twBackgroundColor - https://tailwindcss.com/docs/background-color*/
  twBackgroundColor?: string = ''
  /** twBackgroundOrigin - https://tailwindcss.com/docs/background-origin*/
  twBackgroundOrigin?: string = ''
  /** twBackgroundPosition - https://tailwindcss.com/docs/background-position*/
  twBackgroundPosition?: string = ''
  /** twBackgroundRepeat - https://tailwindcss.com/docs/background-repeat*/
  twBackgroundRepeat?: string = ''
  /** twBackgroundSize - https://tailwindcss.com/docs/background-size*/
  twBackgroundSize?: string = ''
  /** twBackgroundImage - https://tailwindcss.com/docs/background-image*/
  twBackgroundImage?: string = ''
  /** twGradientColorStops - https://tailwindcss.com/docs/gradient-color-stops*/
  twGradientColorStops?: string = ''
  /** twBorderRadius - https://tailwindcss.com/docs/border-radius*/
  twBorderRadius?: string = ''
  /** twBorderWidth - https://tailwindcss.com/docs/border-width*/
  twBorderWidth?: string = ''
  /** twBorderColor - https://tailwindcss.com/docs/border-color*/
  twBorderColor?: string = ''
  /** twBorderStyle - https://tailwindcss.com/docs/border-style*/
  twBorderStyle?: string = ''
  /** twDivideWidth - https://tailwindcss.com/docs/divide-width*/
  twDivideWidth?: string = ''
  /** twDivideColor - https://tailwindcss.com/docs/divide-color*/
  twDivideColor?: string = ''
  /** twDivideStyle - https://tailwindcss.com/docs/divide-style*/
  twDivideStyle?: string = ''
  /** twOutlineWidth - https://tailwindcss.com/docs/outline-width*/
  twOutlineWidth?: string = ''
  /** twOutlineColor - https://tailwindcss.com/docs/outline-color*/
  twOutlineColor?: string = ''
  /** twOutlineStyle - https://tailwindcss.com/docs/outline-style*/
  twOutlineStyle?: string = ''
  /** twOutlineOffset - https://tailwindcss.com/docs/outline-offset*/
  twOutlineOffset?: string = ''
  /** twRingWidth - https://tailwindcss.com/docs/ring-width*/
  twRingWidth?: string = ''
  /** twRingColor - https://tailwindcss.com/docs/ring-color*/
  twRingColor?: string = ''
  /** twRingOffsetWidth - https://tailwindcss.com/docs/ring-offset-width*/
  twRingOffsetWidth?: string = ''
  /** twRingOffsetColor - https://tailwindcss.com/docs/ring-offset-color*/
  twRingOffsetColor?: string = ''
  /** twBoxShadow - https://tailwindcss.com/docs/box-shadow*/
  twBoxShadow?: string = ''
  /** twBoxShadowColor - https://tailwindcss.com/docs/box-shadow-color*/
  twBoxShadowColor?: string = ''
  /** twOpacity - https://tailwindcss.com/docs/opacity*/
  twOpacity?: string = ''
  /** twMixBlendMode - https://tailwindcss.com/docs/mix-blend-mode*/
  twMixBlendMode?: string = ''
  /** twBackgroundBlendMode - https://tailwindcss.com/docs/background-blend-mode*/
  twBackgroundBlendMode?: string = ''
  /** twBlur - https://tailwindcss.com/docs/blur*/
  twBlur?: string = ''
  /** twBrightness - https://tailwindcss.com/docs/brightness*/
  twBrightness?: string = ''
  /** twContrast - https://tailwindcss.com/docs/contrast*/
  twContrast?: string = ''
  /** twDropShadow - https://tailwindcss.com/docs/drop-shadow*/
  twDropShadow?: string = ''
  /** twGrayscale - https://tailwindcss.com/docs/grayscale*/
  twGrayscale?: string = ''
  /** twHueRotate - https://tailwindcss.com/docs/hue-rotate*/
  twHueRotate?: string = ''
  /** twInvert - https://tailwindcss.com/docs/invert*/
  twInvert?: string = ''
  /** twSaturate - https://tailwindcss.com/docs/saturate*/
  twSaturate?: string = ''
  /** twSepia - https://tailwindcss.com/docs/sepia*/
  twSepia?: string = ''
  /** twBackdropBlur - https://tailwindcss.com/docs/backdrop-blur*/
  twBackdropBlur?: string = ''
  /** twBackdropBrightness - https://tailwindcss.com/docs/backdrop-brightness*/
  twBackdropBrightness?: string = ''
  /** twBackdropContrast - https://tailwindcss.com/docs/backdrop-contrast*/
  twBackdropContrast?: string = ''
  /** twBackdropGrayscale - https://tailwindcss.com/docs/backdrop-grayscale*/
  twBackdropGrayscale?: string = ''
  /** twBackdropHueRotate - https://tailwindcss.com/docs/backdrop-hue-rotate*/
  twBackdropHueRotate?: string = ''
  /** twBackdropInvert - https://tailwindcss.com/docs/backdrop-invert*/
  twBackdropInvert?: string = ''
  /** twBackdropOpacity - https://tailwindcss.com/docs/backdrop-opacity*/
  twBackdropOpacity?: string = ''
  /** twBackdropSaturate - https://tailwindcss.com/docs/backdrop-saturate*/
  twBackdropSaturate?: string = ''
  /** twBackdropSepia - https://tailwindcss.com/docs/backdrop-sepia*/
  twBackdropSepia?: string = ''
  /** twBorderCollapse - https://tailwindcss.com/docs/border-collapse*/
  twBorderCollapse?: string = ''
  /** twBorderSpacing - https://tailwindcss.com/docs/border-spacing*/
  twBorderSpacing?: string = ''
  /** twTableLayout - https://tailwindcss.com/docs/table-layout*/
  twTableLayout?: string = ''
  /** twCaptionSide - https://tailwindcss.com/docs/caption-side*/
  twCaptionSide?: string = ''
  /** twTransitionProperty - https://tailwindcss.com/docs/transition-property*/
  twTransitionProperty?: string = ''
  /** twTransitionDuration - https://tailwindcss.com/docs/transition-duration*/
  twTransitionDuration?: string = ''
  /** twTransitionTimingFunction - https://tailwindcss.com/docs/transition-timing-function*/
  twTransitionTimingFunction?: string = ''
  /** twTransitionDelay - https://tailwindcss.com/docs/transition-delay*/
  twTransitionDelay?: string = ''
  /** twAnimation - https://tailwindcss.com/docs/animation*/
  twAnimation?: string = ''
  /** twScale - https://tailwindcss.com/docs/scale*/
  twScale?: string = ''
  /** twRotate - https://tailwindcss.com/docs/rotate*/
  twRotate?: string = ''
  /** twTranslate - https://tailwindcss.com/docs/translate*/
  twTranslate?: string = ''
  /** twSkew - https://tailwindcss.com/docs/skew*/
  twSkew?: string = ''
  /** twTransformOrigin - https://tailwindcss.com/docs/transform-origin*/
  twTransformOrigin?: string = ''
  /** twAccentColor - https://tailwindcss.com/docs/accent-color*/
  twAccentColor?: string = ''
  /** twAppearance - https://tailwindcss.com/docs/appearance*/
  twAppearance?: string = ''
  /** twCursor - https://tailwindcss.com/docs/cursor*/
  twCursor?: string = ''
  /** twCaretColor - https://tailwindcss.com/docs/caret-color*/
  twCaretColor?: string = ''
  /** twPointerEvents - https://tailwindcss.com/docs/pointer-events*/
  twPointerEvents?: string = ''
  /** twResize - https://tailwindcss.com/docs/resize*/
  twResize?: string = ''
  /** twScrollBehavior - https://tailwindcss.com/docs/scroll-behavior*/
  twScrollBehavior?: string = ''
  /** twScrollMargin - https://tailwindcss.com/docs/scroll-margin*/
  twScrollMargin?: string = ''
  /** twScrollPadding - https://tailwindcss.com/docs/scroll-padding*/
  twScrollPadding?: string = ''
  /** twScrollSnapAlign - https://tailwindcss.com/docs/scroll-snap-align*/
  twScrollSnapAlign?: string = ''
  /** twScrollSnapStop - https://tailwindcss.com/docs/scroll-snap-stop*/
  twScrollSnapStop?: string = ''
  /** twScrollSnapType - https://tailwindcss.com/docs/scroll-snap-type*/
  twScrollSnapType?: string = ''
  /** twTouchAction - https://tailwindcss.com/docs/touch-action*/
  twTouchAction?: string = ''
  /** twUserSelect - https://tailwindcss.com/docs/user-select*/
  twUserSelect?: string = ''
  /** twWillChange - https://tailwindcss.com/docs/will-change*/
  twWillChange?: string = ''
  /** twFill - https://tailwindcss.com/docs/fill*/
  twFill?: string = ''
  /** twStroke - https://tailwindcss.com/docs/stroke*/
  twStroke?: string = ''
  /** twStrokeWidth - https://tailwindcss.com/docs/stroke-width*/
  twStrokeWidth?: string = ''
  /** twScreenReaders - https://tailwindcss.com/docs/screen-readers*/
  twScreenReaders?: string = ''
  /** twForcedColorAdjust - https://tailwindcss.com/docs/forced-color-adjust*/
  twForcedColorAdjust?: string = ''
  /** Other variables */
  twOther?:string=''
}

export interface ITailwindTheme extends TailwindTheme { }
export type ITailwindKey = keyof ITailwindTheme;

const keys = Object.keys(new TailwindTheme());

export const isTailwindKey = (propName: string) => keys.includes(propName);

